### ISSUE TITLE
Token Scheme Values

### ISSUE THREAD

**Issue by structure** [cliffom/tokenex-gem#1]
It would be helpful to provide the token scheme mapping for readability. Nice work on the gem.

``` ruby
TOKEN_SCHEME = {sixTOKENfour: 1, fourTOKENfour:2 , ....}
```

http://docs.tokenex.com/#appendix-token-schemes

**Comment by cliffom** [comment]
Great idea, thanks for the feedback.

It looks like the TokenEx docs map the last two schemes to JSON value 17, which may be a mistake. I've reached out to their support to clarify but will move forward with the assumption that `ASCIITOKENAUTO` is actually 18.
